services:
  boodschappen:
    build: .
    container_name: boodschappen
    ports:
      - "2020:8080"
    volumes:
      - ./data:/data
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
